# Generated by Django 4.1.7 on 2023-02-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=13, null=True)),
                ('starpcolor', models.CharField(blank=True, max_length=13, null=True)),
                ('highlights', models.CharField(blank=True, max_length=13, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
