# Generated by Django 4.1.7 on 2023-02-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '1'), ('INACTIVE', '0')], default='ACTIVE', max_length=30),
        ),
    ]
